# Generated by Django 5.0.2 on 2024-03-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_phonenumber_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
    ]
