# Generated by Django 5.0.3 on 2024-04-03 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
