# Generated by Django 5.0.3 on 2024-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
