# Generated by Django 5.0.3 on 2024-04-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_review_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
