# Generated by Django 5.0.3 on 2024-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_review_created_at_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=True, max_length=250, null=True),
        ),
    ]
